# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import re


def extract_task_list(llm_output: str) -> list:
    """
    This function extracts answers from the LLM output which follows the format:
    query: "<query_text>", answer: ["<answer_text>"]
    
    Args:
        llm_output (str): The text generated by the LLM which contains queries and answers.
    
    Returns:
        list: A list of extracted answers from the LLM output.
    """
    pattern = r'answer: \[(.*?)\]'
    
    matches = re.findall(pattern, llm_output)
    
    task_list = [match.strip('"') for match in matches]
    
    return task_list
