# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  agent-tei-embedding-service:
    image: ghcr.io/huggingface/tei-gaudi:latest
    container_name: agent-tei-embedding-server
    ports:
      - "3001:80"
    volumes:
      - ${HF_CACHE_DIR}:/data
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: ${HABANA_VISIBLE_DEVICES}
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      MAX_WARMUP_SEQUENCE_LENGTH: 512
      INIT_HCCL_ON_ACQUIRE: 0
      ENABLE_EXPERIMENTAL_FLAGS: true
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate

  agent-web-retriever:
    image: ${REGISTRY:-opea}/web-retriever-chroma:${TAG:-latest}
    container_name: agent-web-retriever-chroma-server
    ports:
      - "3003:7077"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID}
      LOGFLAG: ${LOGFLAG}
    restart: unless-stopped

networks:
  default:
    driver: bridge
